#!/bin/bash

set -eo pipefail

TMP=/tmp/$(uuidgen)

for f in out/system/system/build.prop out/vendor/build.prop; do
  sed \
    -e 's@,armeabi-v7a@@g' \
    -e 's@,armeabi@@g' \
    -e 's@armeabi-v7a@@g' \
    -e 's@armeabi@@g' \
    $f > $TMP
  cat $TMP > $f
  rm $TMP
done

grep -vE 'dalvik.vm.dex2oat64.enabled=|ro.zygote=' out/vendor/build.prop > $TMP
echo "ro.zygote=zygote64
dalvik.vm.dex2oat64.enabled=true" >> $TMP
cat $TMP > out/vendor/build.prop
rm $TMP

# Explicitly define those to avoid changing odm, product

echo "ro.product.cpu.abilist=arm64-v8a
ro.product.cpu.abilist32=
ro.product.cpu.abilist64=arm64-v8a" >> out/system/system/build.prop

# Use ssgqmigd64
cat out/vendor/bin/ssgqmigd64 > out/vendor/bin/ssgqmigd
rm out/vendor/bin/ssgqmigd64

# Remove 32-bit libraries from /vendor
find out/vendor -name '*.so' -exec file {} + | grep EABI5 | awk -F: '{print $1}' | xargs rm
