#!/bin/bash

set -eo pipefail

TMP=/tmp/$(uuidgen)
FILE=out/vendor/etc/media_codecs_cape_vendor.xml

cp $FILE $TMP
sed -i -e '/    <\/Decoders>/i \
        <MediaCodec name="c2.android.av1.decoder" type="video\/av01" enabled="false" minsdk="100" update="true"> \
        <\/MediaCodec> \
        <MediaCodec name="c2.android.av1-dav1d.decoder" type="video\/av01" enabled="false" minsdk="100" update="true"> \
        <\/MediaCodec>' $TMP
colordiff -Naur $FILE $TMP || true
cat $TMP > $FILE
rm $TMP
