#!/bin/bash

set -eo pipefail

TMP=/tmp/$(uuidgen)

cp out/product/etc/build.prop $TMP
sed -i -e '/ro.sf.lcd_density=/d' $TMP
echo "" >> $TMP
echo "ro.sf.lcd_density=360" >> $TMP
cat $TMP > out/product/etc/build.prop
rm $TMP
