#!/bin/bash

set -eo pipefail

TMP=$(uuidgen)

for f in out/system/system/etc/init/cameraserver.rc out/vendor/etc/init/android.hardware.biometrics.face-service.noth.rc out/vendor/etc/init/vendor.qti.camera.provider@2.7-service_64.rc; do
  cat $f > $TMP
  echo "    setenv JE_MALLOC_ZERO_FILLING 1" >> $TMP
  sed -i -e '/^$/d' $TMP
  cat $TMP > $f
  rm $TMP
  file $f
  batcat $f
done
