#!/bin/bash

set -eo pipefail

VERSION="-arter97-r22"

TMP=/tmp/$(uuidgen)

# Version
sed -e "/ro.nothing.version.id=/ s/\$/${VERSION}/" out/system/system/build.prop > $TMP
cat $TMP > out/system/system/build.prop
rm $TMP

# DPI
cp out/product/etc/build.prop $TMP
sed -i -e '/ro.sf.lcd_density=/d' $TMP
echo "" >> $TMP
echo "ro.sf.lcd_density=360" >> $TMP
cat $TMP > out/product/etc/build.prop
rm $TMP

# Volume
echo "ro.config.media_vol_steps=30" >> out/system/system/build.prop
echo "audio.safemedia.bypass=true" >> out/system/system/build.prop

# Fix Dirac from ro.config.media_vol_steps=30
sed -e 's@"max": 16@"max": 30@g' -e 's@"default": 10,@"default": 28,@g' out/vendor/etc/dirac/interface.json > $TMP
colordiff -Naur out/vendor/etc/dirac/interface.json $TMP || true
cat $TMP > out/vendor/etc/dirac/interface.json
rm $TMP

# Disable logd to forward kernel logs to logcat
echo "ro.logd.kernel=false" >> out/system/system/build.prop

# Disable LayerExt
cp out/vendor/build.prop $TMP
sed -i -e '/vendor.display.use_layer_ext/d' $TMP
cat $TMP > out/vendor/build.prop
rm $TMP
