#!/bin/bash

set -eo pipefail

VERSION="-arter97-r8"

TMP=/tmp/$(uuidgen)

sed -e "/ro.nothing.version.id=/ s/\$/${VERSION}/" out/system/system/build.prop > $TMP
cat $TMP > out/system/system/build.prop
rm $TMP
