#!/bin/bash

set -eo pipefail

TMP=/tmp/$(uuidgen)

echo "Patching for viper"

cd out/
find vendor -name '*audio_effects*' | while read FILE; do
  case $FILE in
    *.conf)
        sed \
          -e "/v4a_re {/,/}/d" \
          -e "s/^effects {/effects {\n  v4a_re {\n    library v4a_re\n    uuid 90380da3-8536-4744-a6a3-5731970e640f\n    type b9bc100c-26cd-42e6-acb6-cad8c3f778de\n  }/g" \
          -e "s/^libraries {/libraries {\n  v4a_re {\n    path \/vendor\/lib\/soundfx\/libv4a_re.so\n  }/g" \
          $FILE > $TMP
        colordiff -Naur $FILE $TMP || true
        cat $TMP > $FILE
        ;;
    *.xml)
        sed \
          -e "/v4a_re/d" \
          -e "/<libraries>/ a\        <library name=\"v4a_re\" path=\"libv4a_re.so\"\/>" \
          -e "/<effects>/ a\        <effect name=\"v4a_re\" library=\"v4a_re\" uuid=\"90380da3-8536-4744-a6a3-5731970e640f\" type=\"b9bc100c-26cd-42e6-acb6-cad8c3f778de\"\/>" \
          $FILE > $TMP
        colordiff -Naur $FILE $TMP || true
        cat $TMP > $FILE
        ;;
  esac
done

cd ..
rm $TMP
